#reads or bam input format options
input_format: "reads"

#------------------------------------
# Resource options
#------------------------------------
resources: "/Users/margotlavitt/resources/"
# Mapping file from alignment (Default: MGV viruses)
mapping: "/Users/margotlavitt/resources/input/instrain_test_data/all_genomes.fasta"
gene_fasta: ""
gene_fna: "/Users/margotlavitt/resources/input/instrain_test_data/all_genomes_genes.fna"

#------------------------------------
# Analysis options
#------------------------------------
results: "/Users/margotlavitt/Sum22/HoffLab_InStrain/results/"

#------------------------------------
# Rule customization 
#------------------------------------
min_breadth: 50
### Extra Args ###
inStrain_profile_extra_args: ""
inStrain_compare_extra_args: ""